name: Publish Release

on:
  release:
    types:
    - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        export MVN_ARGS="-DbuildNumberSuffix="
        mvn ${MVN_ARGS} package
        echo "::set-env name=FILENAME::$(mvn ${MVN_ARGS} org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.build.finalName -q -DforceStdout)"
    - name: Upload JAR
      uses: jasonetco/upload-to-release@v0.1.1
      with:
        args: target/${{ env.FILENAME }}.jar application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
